version: '3'
services:
  web:
    build: .
    restart: always
    volumes:
      - "./send-form.php:/var/www/html/send-form.php"
      - "./assets:/var/www/html/assets"
      - "./config:/var/www/html/config"
      - "./content:/var/www/html/content"
      - "./themes/cmdev:/var/www/html/themes/cmdev"
    env_file:
      - mail.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.cmdsite.rule: "Host(`cmd-ev.de`) || Host(`www.cmd-ev.de`)"
      traefik.http.routers.cmdsite.entrypoints: "web"
      traefik.http.routers.cmdsite.middlewares: "redirect-to-https@file, add-sts-with-subdomains@file"
      traefik.http.routers.cmdsitesecure.rule: "Host(`cmd-ev.de`) || Host(`cmdsite.cmd-ev.de`)"
      traefik.http.routers.cmdsitesecure.tls.certresolver: "le"
      traefik.http.routers.cmdsitesecure.entrypoints: "websecure"
      traefik.http.routers.cmdsitesecure.middlewares: "add-sts-with-subdomains@file"

networks:
  default:
    external:
      name: web

