version: '3'
services:
  web:
    build: .
    #restart: always
    volumes:
      - "./send-form.php:/var/www/html/send-form.php"
      - "./assets:/var/www/html/assets"
      - "./config:/var/www/html/config"
      - "./content:/var/www/html/content"
      - "./themes/cmdev:/var/www/html/themes/cmdev"
    env_file:
      - mail.env
